#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_


#undef REST_MAX_CHUNK_SIZE
#define REST_MAX_CHUNK_SIZE 96
#undef COAP_MAX_OPEN_TRANSACTIONS
#define COAP_MAX_OPEN_TRANSACTIONS 4

#undef NBR_TABLE_CONF_MAX_NEIGHBORS
#define NBR_TABLE_CONF_MAX_NEIGHBORS 10

#undef UIP_CONF_MAX_ROUTES
#define UIP_CONF_MAX_ROUTES 10

#undef UIP_CONF_BUFFER_SIZE
#define UIP_CONF_BUFFER_SIZE 240

#define CCXXWARE_CONF_ROM_BOOTLOADER_ENABLE 1

#define LOG_LEVEL_APP LOG_LEVEL_DBG
#define IEEE802154_CONF_PANID            0xABCD
#define IEEE802154_CONF_DEFAULT_CHANNEL      25

#endif /* PROJECT_CONF_H_ */